defmodule SpellfinderWeb.Schemas.RawSpell do
  @moduledoc """
  Schema for Raw Spell entries in the Raw Spells table. This is the flat data that will later be normalized.
  """
  use Ecto.Schema

  schema "raw spell" do
    field :name, :string
    field :school, :string
    field :subschool, :string
    field :descriptor, :string
    field :spell_level, :string
    field :casting_time, :string
    field :components, :string
    field :costly_components, :boolean
    field :range, :string
    field :area, :string
    field :effect, :string
    field :targets, :string
    field :duration, :string
    field :dismissible, :boolean
    field :shapeable, :boolean
    field :saving_throw, :boolean
    field :spell_resistance, :string
    field :description, :string
    field :description_formatted, :string
    field :source, :string
    field :full_text, :string
    field :verbal, :boolean
    field :somatic, :boolean
    field :material, :boolean
    field :focus, :boolean
    field :divine_focus, :boolean
    field :sor, :integer
    field :wiz, :integer
    field :cleric, :integer
    field :druid, :integer
    field :ranger, :integer
    field :bard, :integer
    field :paladin, :integer
    field :alchemist, :integer
    field :summoner, :integer
    field :witch, :integer
    field :inquisitor, :integer
    field :oracle, :integer
    field :antipaladin, :integer
    field :magus, :integer
    field :adept, :integer
    field :deity, :integer
    field :SLA_Level, :string
    field :domain, :string
    field :short_description, :string
    field :acid, :boolean
    field :air, :boolean
    field :chaotic, :boolean
    field :cold, :boolean
    field :curse, :boolean
    field :darkness, :boolean
    field :death, :boolean
    field :disease, :boolean
    field :earth, :boolean
    field :electricity, :boolean
    field :emotion, :boolean
    field :evil, :boolean
    field :fear, :boolean
    field :fire, :boolean
    field :force, :boolean
    field :good, :boolean
    field :language_dependent, :boolean
    field :lawful, :boolean
    field :light, :boolean
    field :mind_affecting, :boolean
    field :pain, :boolean
    field :poison, :boolean
    field :shadow, :boolean
    field :sonic, :boolean
    field :water, :boolean
    field :linktext, :string
    field :raw_id, :integer
    field :material_costs, :integer
    field :bloodline, :string
    field :patron, :string
    field :mythic_text, :string
    field :augmented, :string
    field :mythic, :boolean
    field :bloodrager, :integer
    field :shaman, :integer
    field :psychic, :integer
    field :medium, :integer
    field :mesmerist, :integer
    field :occultist, :integer
    field :spiritualist, :integer
    field :skald, :integer
    field :investigator, :integer
    field :hunter, :integer
    field :haunt_statistics, :string
    field :ruse, :boolean
    field :draconic, :boolean
    field :meditative, :boolean
    field :summoner_unchained, :integer
  end
end
